# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190530_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='null', upload_to='media/'),
            preserve_default=False,
        ),
    ]
