# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190531_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order', to='store.Product'),
        ),
    ]
