# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
